/*
 *  TowheeAtomPositionDefinition.h
 *  API Glue
 *
 */

#ifndef TOWHEE_ATOMPOSDEF_WRAPPER_H
#define TOWHEE_ATOMPOSDEF_WRAPPER_H

#include "TowheeInterfaceAtomPositionDefinition.h"
#include "IAPIMolecule.h"
#include "IAPIVector.h"

using namespace molesimAPI;

namespace towheewrappers
{

    /**
      * TowheeAtomPositionDefinition has no practical application outside
      * of the Towhee API glue layer.  It is necessary only for a class
      * to hold method(s) generated by parsers used to create a java proxy
      * class layer.
      * @todo This class should be removed.
      */
    class TowheeAtomPositionDefinition : public virtual TowheeInterfaceAtomPositionDefinition {

        public:			

            // API Compliance
            IAPIVector *position(IAPIMolecule *atom) {};


    };
}
#endif
